# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 07:49
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.AutoField(db_column='PatientID', primary_key=True, serialize=False)),
                ('pyear', models.DecimalField(blank=True, db_column='Pyear', decimal_places=0, max_digits=10, null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('fname', models.TextField(blank=True, db_column='FName', null=True)),
                ('lname', models.TextField(blank=True, db_column='LName', null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='DOB', null=True)),
                ('pamonth', models.TextField(blank=True, db_column='PAMonth', null=True)),
                ('payear', models.TextField(blank=True, db_column='PAYear', null=True)),
                ('padays', models.TextField(blank=True, db_column='PADays', null=True)),
                ('sex', models.TextField(blank=True, db_column='Sex', null=True)),
                ('rdate', models.DateTimeField(blank=True, db_column='rDate', default=datetime.datetime(2017, 4, 11, 13, 19, 28, 510069), null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('pin', models.TextField(blank=True, db_column='Pin', null=True)),
                ('phone', models.TextField(blank=True, db_column='Phone', null=True)),
                ('cellular', models.TextField(blank=True, db_column='Cellular', max_length=10, null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='presciptiontemplates',
            fields=[
                ('templateid', models.AutoField(primary_key=True, serialize=False)),
                ('template', ckeditor.fields.RichTextField()),
                ('draft', models.BooleanField(default=False)),
                ('savedate', models.DateTimeField(default=datetime.datetime(2017, 4, 11, 13, 19, 28, 511069))),
                ('patientid', models.IntegerField()),
            ],
        ),
    ]
